### ISSUE TITLE
Site -> Address fields

### ISSUE THREAD

**Issue by amymallen** [hmis-interop/xml#102]
Should this provider address be the one indicated by the user as Primary, the physical address, or the mailing address?

**Comment by eric-jahn** [comment]
@amymallen: Just looking at the 2015/v3.1 Data Dictionary (what the XSD is udirectly based on) I see this: 

2.8 Site Information - OPTIONAL
Field 1 & Responses Principal Site
0 No
1 Yes
Dependent A – Dependent to If Yes to “Principal Site” –
Field 1 & Response HUD Geocode
Field 2 & Response Street Address
Field 3 & Response City
Field 4 & Response State
Field 5 & Response Zip Code

So you only complete this if it's the principal site.  I think by "primary" you mean HMIS' "principal site"?   As far as physical versus mailing address, I don't think HMIS makes that distinction.   I might be wrong about that though, and HUD might  have some guidance on the topic.  My instinct is that, since we are also involving the HUD Geocode, it's [whatever address contributes to Geocode determination](https://www.hudexchange.info/resources/documents/HUDGISToolTutorial.pdf), and geography = physical?  That said, I think you may have led me to identify a bug (sort of related): https://github.com/hmis-interop/logical-model/issues/12

**Comment by eric-jahn** [comment]
and I assumed with my answer you were talking about the 2015/v3.1 Data Standard , but if you were talking about 2014/v3.0 Data Standard, the same applies (except there is no bug related to 2014/v3.1 Data Standard)
