### ISSUE TITLE
Inventory Cardinality Constraint

### ISSUE THREAD

**Issue by jimosullivan1099** [hmis-interop/xml#133]
Hi Eric,

There is a discrepancy in the XML, and Data Dictionary vs the CSV and Data Manual.  

The XSD has it to where you can only have 1 active inventory per ProjectID/CoCCode however in the CSV and Data Manual, you can have more than 1 active Inventory  per CocCode as long as they serve different household types. 

The XSD has
`<xs:keyref name="inventoryProjectCoCKeyRef" refer="projectCoCKey">
    <xs:selector xpath="hmis:Inventory"/>
    <xs:field xpath="hmis:ProjectID"/>
    <xs:field xpath="hmis:CoCCode"/>    
</xs:key>`

but the Data Manual states:

![image (7)](https://user-images.githubusercontent.com/5349227/66932748-f009b880-efec-11e9-8ed7-a6ac6fcc1a69.png)

The CSV spec also has:

`There may be multiple records in Inventory.csv:
• For each combination of ProjectID and CoCCode in ProjectCoC.csv where ProjectType in
Project.csv is equal to 1,2,3,8,9,10, or 13;
• For each Household Type, Target Population, Housing Type and/or Bed Type in a single project;`

Jim

**Comment by eric-jahn** [comment]
@jimosullivan1099, I think that the XML Schema already allows for multiple Inventories per ProjectCoC.  The stanza 
```
<xs:keyref name="inventoryProjectCoCKeyRef" refer="projectCoCKey">
    <xs:selector xpath="hmis:Inventory"/>
    <xs:field xpath="hmis:ProjectID"/>
    <xs:field xpath="hmis:CoCCode"/>
</xs:keyref>
```
only ensures that the ProjectID foreign key points to a present ProjectID, and same for CoCCode.  That stanza does nothing to enforce cardinality.  I verified this by taking the [minimal XML instance](https://github.com/hmis-interop/xml/blob/latest/src/HUD_HMIS_Instance_minimal_for_testing.xml) and adding another Inventory to with just a different InventoryID, and it still validated.  

We could put something in to enforce Inventory cardinality per project, with an assertion like:

```
<xs:assert test="every $id in hmis:Inventory/hmis:ProjectID satisfies (fn:count(hmis:Inventory[hmis:ProjectID = $id]) ge 0)"/>

```

I just tend to leave those out, because it entails extra validation processing just to allow any number of occurrences.
