### ISSUE TITLE
Could you please re-generate files in xml/doc/ ?

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#164]
Hi @eric-jahn ,

Recently xml schema has been changed several times. Could you please regenerate documents in xml/doc/ ?

BTW, when changes made in V2022 will be merged in master?

Thank you,
Natalie

**Comment by eric-jahn** [comment]
Yes, I'll regenerate the schema docs soon.  

For the branches, v2022 and prior versions remain in their own branches over time, as the official repo for that version.  And then we keep maintaining those branches.  In the past, I would do a merge from the latest branch, to the main branch, right before working on a new version just before I branch off a new version.  I wouldn't point anything at main though, since it doesn't really represent a latest production version of anything, since that all maintenance changes for each version happen in each branch.  And older versioned branches continue to be maintained over time, without merges to main (usually not at least).

**Comment by nataliesus** [comment]
Thank you, @eric-jahn ! Just in case, please be sure to regenerate the schema docs for both FY 2020 and FY 2022. It will help us a lot because we are in the report refactoring process so it is easy for us to use docs than go through the real schema. Thank you!

**Comment by eric-jahn** [comment]
FY2020 docs also now regenerated, to include some recent changes.
