### ISSUE TITLE
Disabilities -> missing PersonalID

### ISSUE THREAD

**Issue by volkovai** [hmis-interop/xml#176]
Hi @eric-jahn ,

In CSV specification, there is said "The unique identifier for Client.csv is 5.08 Personal Identifier (PersonalID), which is used to associate data **in other CSV files** with a specific person."

In Disabilities part of XML schema, there is no PersonalID field.

Could you please confirm/correct this is an issue or not?

Thank you,
Irina

**Comment by eric-jahn** [comment]
No this is not an issue, since the CSV has unnecessary additional foreign keys for ID matching convenience across files, but the XML being a single file, more closely adheres to the Logical Model which has the Disabilities dependent only upon the Enrollment.
![dis](https://user-images.githubusercontent.com/4115079/131765187-e69813e8-5f73-4376-a2a5-63e4798267f4.png)
