### ISSUE TITLE
PathStatus: discrepancies between XML and CSV spec

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#188]
Hi @eric-jahn ,

**#1.** There is a discrepancy between the list of allowed values for _ReasonNotEnrolled_ field:
XML:
![image](https://user-images.githubusercontent.com/28144855/132487335-bcc444d7-a6e3-4b5a-9c8f-de914cdc555a.png)

CSV:
![image](https://user-images.githubusercontent.com/28144855/132495194-7872aad6-37f3-4c1e-8894-6ac0457caf35.png)

**#2.** Field name discrepance: _DateOfStatus_ in XML but _DateOfPATHStatus_ in CSV.

**#3.** Mandatory/optional flag settings are different in XML and CSV for fields _DateOfStatus_ and _ClientEnrolledInPATH_

XML:
![image](https://user-images.githubusercontent.com/28144855/132495978-498cc724-5cd8-47b0-a801-9b8b5d9bfd3c.png)

CSV:
![image](https://user-images.githubusercontent.com/28144855/132495993-0ad4f6b7-344e-448a-a1b7-ce84213bf4fc.png)

Could you please take a look?

Thank you!
Natalie

**Comment by eric-jahn** [comment]
Fixed #1 and #2, thank you!  For #3, the XML's cardinality is correct, since the status requires a date and a status.  Unlike for the CSV, if either of those two data elements are not collected, the whole PATHStatus element with its complex type sequence can be effectively omitted, and achieve the same result as having the complex type with contained null values.
