### ISSUE TITLE
RHYBCPStatus->ReasonNoServices: discrepancy between XML and CSV

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#191]
Hi @eric-jahn,

There is a discrepancy between the list of allowed values for ReasonNoServices field:
XML:
![image](https://user-images.githubusercontent.com/28144855/132844659-2992cee3-27f2-444b-a8f5-51f1487f01e5.png)

CSV:
![image](https://user-images.githubusercontent.com/28144855/132844674-08e0cfe4-8f69-417a-8fc4-f26593610e0e.png)

Could you please take a look?

Thank you!
Natalie

**Comment by nataliesus** [comment]
Hi @eric-jahn ,

What is about FY2022? It should also be fixed:
![image](https://user-images.githubusercontent.com/28144855/133102706-bb137af5-3a9c-419b-8f2e-2500f58bb24a.png)

**Comment by eric-jahn** [comment]
@nataliesus I think you're right, but not because of an FY2022 CSV discrepancy.  CSV FY2022 (at least in August, so maybe they fixed it in Sept., I have to check) has 99 as an option.  
![rns](https://user-images.githubusercontent.com/4115079/133104672-2d8f6717-c2e9-4468-afac-816db6ce69a5.png)


But the Manual and Dictionary omitted the 99.  So I'll check if CSV has since been fixed and if not, file a CSV issue.

**Comment by eric-jahn** [comment]
I was told by HMIS TA that the CSV is correct for FY2022, and the Dictionary does not need to be updated for this.  So, I'm re-closing the issue.
